### PR TITLE
Add a DataSource bound to a CF RDBMS service for the task tables

### LINKED ISSUE #27: Add a DataSource for the task database
The spring-cloud-dataflow-admin-starter now creates the task database tables on start-up. All SPI implementations should add a DataSource to their configuration to be used for the tasks.

### PR DESCRIPTION
**Pull request by trisberg**
Resolves #27

### CODE REVIEW

**Comment by markpollack** [comment]
I don't think this error is related, but on CF for time | log with this admin server, the admin server starts up find (i bound a mysql and redis to the admin) but the log module is giving me this error.  

I don't quite get understand why the ticktock-log app should be looking for a database.

```
2016-01-22T23:07:47.000+00:00 [APP] OUT 2016-01-22 23:07:47.044 WARN 11 --- [ main] o.s.c.s.relational.DataSourceCreator : No connection pooling DataSource implementation found on the classpath - no pooling is in effect.
2016-01-22T23:07:47.000+00:00 [APP] OUT 2016-01-22 23:07:47.052 ERROR 11 --- [ main] o.s.boot.SpringApplication : Application startup failed
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:133) ~[spring-cloud-core-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT java.lang.NoClassDefFoundError: org/springframework/jdbc/datasource/SimpleDriverDataSource
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:63) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:26) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:245) ~[spring-cloud-core-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createService(AbstractCloudServiceConnectorFactory.java:105) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createInstance(AbstractCloudServiceConnectorFactory.java:99) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.config.java.ServiceScanConfiguration.registerBeanDefinitions(ServiceScanConfiguration.java:22) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:134) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.afterPropertiesSet(AbstractCloudServiceConnectorFactory.java:94) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.config.CloudScanHelper.registerServiceBean(CloudScanHelper.java:93) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.config.CloudScanHelper.registerServiceBeans(CloudScanHelper.java:59) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.config.java.CloudScanConfiguration.registerBeanDefinitions(CloudScanConfiguration.java:22) ~[spring-cloud-spring-service-connector-1.2.1.RELEASE.jar!/:na]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:352) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
2016-01-22T23:07:47.000+00:00 [APP] OUT at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.cloud.stream.module.log.LogSinkApplication.main(LogSinkApplication.java:26) [log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
2016-01-22T23:07:47.000+00:00 [APP] OUT at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
2016-01-22T23:07:47.000+00:00 [APP] OUT at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
2016-01-22T23:07:47.000+00:00 [APP] OUT Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.datasource.SimpleDriverDataSource
2016-01-22T23:07:47.000+00:00 [APP] OUT at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178) ~[log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
2016-01-22T23:07:47.000+00:00 [APP] OUT at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_65-]
2016-01-22T23:07:47.000+00:00 [APP] OUT ... 34 common frames omitted 
```

**Comment by trisberg** [comment]
Strange, works for me:

```
2016-01-22T19:51:19.24-0500 [APP/0]      OUT 2016-01-23 00:51:19.249  INFO 11 --- [           main] o.s.c.s.module.log.LogSinkApplication    : Started LogSinkApplication in 12.646 seconds (JVM running for 24.965)
2016-01-22T19:51:19.33-0500 [HEALTH/0]   OUT healthcheck passed
2016-01-22T19:51:19.34-0500 [HEALTH/0]   OUT Exit status 0
2016-01-22T19:51:21.46-0500 [APP/0]      OUT 2016-01-23 00:51:21.463  INFO 11 --- [hannel-adapter1] log.sink                                 : 01/23/16 00:51:21
2016-01-22T19:51:22.45-0500 [APP/0]      OUT 2016-01-23 00:51:22.453  INFO 11 --- [hannel-adapter1] log.sink                                 : 01/23/16 00:51:22
2016-01-22T19:51:23.45-0500 [APP/0]      OUT 2016-01-23 00:51:23.456  INFO 11 --- [hannel-adapter1] log.sink                                 : 01/23/16 00:51:23
```

What does the log entry for the ModuleLauncherRunner look like? I have:

```
2016-01-22T19:51:02.86-0500 [APP/0]      OUT 2016-01-23 00:51:02.861  INFO 11 --- [           main] o.s.c.s.m.launcher.ModuleLauncherRunner  : Launching
2016-01-22T19:51:02.86-0500 [APP/0]      OUT 	org.springframework.cloud.stream.module:log-sink:jar:exec:1.0.0.BUILD-SNAPSHOT with arguments {spring.cloud.stream.bindings.input.destination=s.0, dataflow.group-deployment-id=s-1453510194816, spring.jmx.default-domain=s.log}
```

**Comment by markpollack** [comment]
I guess I don't have access to the logs anymore once the app is killed.  Is that right?  What PCF environment are you using?  I was using the 'baby' environment.

**Comment by markpollack** [comment]
I'll run it again and get that log entry

**Comment by markpollack** [comment]
The admin only depend on one persistent store.  Is there another issue to add a relational stream repo and module registry?

**Comment by mbogoevici** [comment]
@markpollack Not sure how helpful is this, but this behavior is what you'd get if `ticktock-log` were to have the ``mysql` service bound to it, either directly via stream deployment props, or via `cloudfoundry.services` .

**Comment by trisberg** [comment]
I would think that a relational stream repo and registry would use the same database as the task. I think the "navy" environment was having some issues and is being rebuilt, maybe try this again once that is available or I can set you up on the "ivory" environment that I'm using.

**Comment by markpollack** [comment]
I did bind MySQL and redis via the set-env commands when deploying the admin, but I did not thing that would carry over to the apps that the admin deploys.

**Comment by trisberg** [comment]
The mysql service should not be bound to the stream apps, only redis should be bound for the message bus. Did you deploy and restart the admin with the latest bits? For my testing only redis is bound to the apps that are part of the stream.

**Comment by mbogoevici** [comment]
@markpollack The `cf set-env CLOUDFOUNDRY_SERVICES=xyz` command tells the admin server what services to bind to each launched instance (and defaults to just redis since that's what the binders use) - so if you set things there, then it works as expected. The services bound to the admin server are provided via `cf bind-service`.

**Comment by mbogoevici** [comment]
Maybe we should rename the property, to make it clear it refers to the services bound by the launched applications, not the admin server itself.

**Comment by trisberg** [comment]
Agree, maybe the env var should be something like MESSAGE_BROKER_SERVICE or
something similar.

On Mon, Jan 25, 2016 at 11:10 AM, Marius Bogoevici <notifications@github.com

**Comment by markpollack** [comment]
Having a DATAFLOW prefix would be useful ...

**Comment by markpollack** [comment]
Also, with the likely upcoming work to have our ootb modules be available for specific binders, passing a property to the admin wrt what default binder/message broker to prefer would be generally useful across all admins.

**Pull request closed without merging**
