### PR TITLE
Add ModuleDeployer ITs

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#22

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/pull/293

### CODE REVIEW

**Comment by ericbottard** [comment]
Note: we'll need to come up with a way to
1) only enable those tests if we have a CF instance at hand
2) pass credentials in a safe way (config server maybe)?

**Comment by ilayaperumalg** [comment]
After applying the credentials, the tests fail with only first test being succeeded. Is there a cleanup step missing?

The errors say:

```
ailed tests:
  ApplicationModuleDeployerTests>AbstractModuleDeployerTests.assertCleanStart:69 A newly created deployer should report no modules (this error may be caused by a previous test failing and not cleaning after itself)
Expected: is <true>
     but: was <false>
  ApplicationModuleDeployerTests>AbstractModuleDeployerTests.assertCleanStart:69 A newly created deployer should report no modules (this error may be caused by a previous test failing and not cleaning after itself)
Expected: is <true>
     but: was <false>
  ApplicationModuleDeployerTests>AbstractModuleDeployerTests.testRedeploy:127
Expected: hasProperty("state", is <deployed>), trying at most 12 times
     but: failed after 12*5000=60000ms:
```

**Comment by ericbottard** [comment]
Yes, this is a message to help diagnose the real cause of a failure. It can be disregarded, and the failure of the previous test should be looked into

**Comment by ericbottard** [comment]
I think we need to add a `@Rule` for CF availability, similar to what we have for rabbit, redis, etc.

**Comment by ilayaperumalg** [comment]
@ericbottard I keep getting this test failure:

```
testRedeploy(org.springframework.cloud.dataflow.module.deployer.cloudfoundry.ApplicationModuleDeployerTests)  Time elapsed: 625.635 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: hasProperty("state", is <deployed>), trying at most 12 times
     but: failed after 12*5000=60000ms:
status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>, status of <6de29c2f-6bbe-461c-b17d-21233ba188bc.d8d35d06-f5f2-46ab-b091-f797a7a54c5a> property 'state' was <failed>,
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.springframework.cloud.dataflow.module.deployer.test.AbstractModuleDeployerTests.testRedeploy(AbstractModuleDeployerTests.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by ericbottard** [comment]
Do you know why the deployment failed? I'll give it another run on my env

**Comment by ilayaperumalg** [comment]
Looks like the problem happens when the ModuleResolver property for `localRepository` gets created.

```
ERR Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.stream.module.resolver.ModuleResolver]: Factory method 'moduleResolver' threw exception; nested exception is java.lang.IllegalArgumentException: Unable to create directory for local repository: /Users/igopinatha/.m2/repository
2016-01-27T08:32:09.000+00:00 [APP] ERR at org.springframework.cloud.stream.module.resolver.AetherModuleResolver.<init>(AetherModuleResolver.java:97)
```

Does the test require to override this property?

**Comment by ericbottard** [comment]
no, but how can that path make sense on CF?
Did it propagate from your env to CF somehow?

Or is this log local? (but then how did it go through to trying to deploy?) o.O

**Comment by ericbottard** [comment]
OK, updated the PR with the latest dataflow. Made tests run only when a CF install is reachable (driven by same `cloudfoundry.*` properties as what is used for the deployer).

This requires https://github.com/spring-cloud/spring-cloud-dataflow/issues/417 to run properly _via_ maven.

**Comment by ericbottard** [comment]
Updated PR

**Comment by ilayaperumalg** [comment]
LGTM. Verified running the build against CF environment after setting the CF endpoint properties.
Rebased and merged as 40447b4f140a6ec3e3cd32a7224915843278b4f8

**Pull request closed without merging**
