### PR TITLE
Use correct parent pom location

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#54

### CODE REVIEW

**Comment by jvalkeal** [comment]
Think your local build is using old deps as:
```
[ERROR] /home/jvalkealahti/repos/spring/spring-cloud-dataflow-admin-cloudfoundry/spring-cloud-dataflow-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryModuleDeployerConfiguration.java:[24,55] package org.springframework.cloud.dataflow.admin.config does not exist
[ERROR] /home/jvalkealahti/repos/spring/spring-cloud-dataflow-admin-cloudfoundry/spring-cloud-dataflow-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryModuleDeployerConfiguration.java:[43,13] cannot find symbol
[ERROR] symbol:   class AdminProperties
[ERROR] location: class org.springframework.cloud.dataflow.module.deployer.cloudfoundry.CloudFoundryModuleDeployerConfiguration
```

`CloudFoundryModuleDeployerConfiguration` is still using `org.springframework.cloud.dataflow.admin.config.AdminProperties` and admin was renamed to server last night.

**Comment by ericbottard** [comment]
The rename from `AdminProperties` is taken care of as part of https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/pull/23, which @ilayaperumalg is looking at

**Comment by jvalkeal** [comment]
right, ok.

**Comment by ilayaperumalg** [comment]
LGTM, merged as 62b2d00bf7f7701400f45f255312147e88117939.

**Pull request merged**
